# disable in production:  
local_backend: true
# command to run a local Decap instance: npx-decap-server

backend:
  name: github
  repo: your-username/your-repo   # GitHub repo where content lives
  branch: main

media_folder: "public/upload"
public_folder: "/"

site_url: https://gco-cms.netlify.app

media_library:
  name: cloudinary
  # output_filename_only: true
  config:
    cloud_name: <YOUR_CLOUD_NAME_HERE>
    api_key: <YOUR_API_KEY_HERE> 


# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields: 
    - { name: "metaTitle", label: "SEO Title", widget: "string", default: "{{ title }}", required: true }
    - { name: "metaDescription", label: "SEO Description", widget: "string", pattern: [".{20,160}", "between 20 and 160 characters"], required: true, hint: "must be between 20 and 160 characters" }
    - { name: "metaImage", label: "SEO image", widget: "image"}
    - { name: "keywords", label: "keywords", widget: "string", hint: "keywords are comma seperated", required: false }

collections:
  - name: "globalContent"
    label: "global content"
    create: true
    files: 
      - label: "buttons"
        name: "buttons"
        file: "content/site/buttons.md"    
        fields: 
          - label: "next"
            name: "next"
            widget: "string"        
          - label: "previous"
            name: "previous"
            widget: "string"        
          - label: "close"
            name: "close"
            widget: "string"        
          - label: "article: more"
            name: "article"
            widget: "string"
            default: "read more"
          - label: "form: send"
            name: "send"
            widget: "string"
        
  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    create: true
    folder: "contents/pages"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
      - *seo
  
  - name: "news"                # used in filenames, must be unique
    label: "News"               # shows in CMS sidebar
    folder: "content/news"      # where markdown files live
    create: true                 # enables "New Post" button
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Picture", name: "picture", widget: "image" }  # 👈 added
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

